# Generated by Django 5.0.3 on 2024-03-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('fullName', models.CharField(max_length=250)),
                ('registrationDate', models.DateField()),
                ('dateOfBirth', models.DateField()),
                ('phoneNumber', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('education_level', models.CharField(max_length=100)),
                ('graduationDate', models.DateField()),
                ('employmentStatus', models.CharField(max_length=100)),
                ('experienceYears', models.PositiveBigIntegerField()),
                ('doYouHaveCompany', models.CharField(max_length=50)),
                ('yourBusinessName', models.CharField(max_length=250)),
                ('yourBusinessStage', models.CharField(max_length=250)),
                ('DateOfYourBusinessEstablishment', models.DateField()),
                ('totalFoundersInYourBusiness', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
