# Generated by Django 5.0.3 on 2024-03-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='doYouHaveCompany',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='education_level',
            field=models.CharField(choices=[('Primary level', 'Primary level'), ('Secondary level', 'Secondary level'), ('Tartiary level', 'Tartiary level')], max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='employmentStatus',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Self-employed', 'Self-employed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='totalFoundersInYourBusiness',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='yourBusinessName',
            field=models.CharField(default='N/A', max_length=250),
        ),
        migrations.AlterField(
            model_name='application',
            name='yourBusinessStage',
            field=models.CharField(choices=[('Start up', 'Start up'), ('Growth', 'Growth'), ('Marturity', 'Marturity'), ('Renewal', 'Renewal'), ('Decline', 'Descline')], default='N/A', max_length=250),
        ),
    ]
