# Generated by Django 5.0.3 on 2024-04-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_application_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
    ]
